### ISSUE TITLE
DHCP server shouldn't need complex address setup

### ISSUE THREAD

**Issue by TommyPec** [TommyPec/ns-3-dev-dhcp#2]
Investigate (and remove) horrible "hack" in DHCP server node addressing

**Comment by TommyPec** [comment]
The bogus assignment can be removed once we sync with the latest ns-3-dev.
In ns-3-dev it is not anymore needed any trick to send a packet to 255.255.255.255

**Comment by adeepkit01** [comment]
Any specific reason behind the git and mercurial of ns-3-dev being out of sync for past 2-3 days? (I just think it will be easier to sync the commits if we pull the up to date git repository)

**Comment by TommyPec** [comment]
I asked Vedran (the repo owner). Still no answer.

**Comment by TommyPec** [comment]
I fixed the repo syncing, and now it should be possible to fix this part.

**Comment by TommyPec** [comment]
This problem has been automagically fixed by the changes in the upstream repository.
The "trick" is not anymore needed and removing it is totally ok.
